config/routes.rb
Projekts::Application.routes.draw do
  get 'admin' => 'admin#index'

   controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :feeds

  resources :user_sports

  get 'admin/index' 

  get 'sessions/new', as: 'sign_up'

  post 'user_sports' => 'user_sports#create'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :news

  resources :my_profiles

  resources :sports

  get "users/index"

  resources :users

  root 'news#index', via: :all
  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
	SPORTS = [
	["Hokejs", 				1],
	["Basketbols", 			2],
	["Futbols", 			4],
	["Volejbols", 			5],	
	["Florbols", 			6],
	["Handbols", 			7],
	["Motoru sports", 		12],
	["Vieglatlētika", 		16],
	["Riteņbraukšana",		17],
	["Pludmales volejbols",	18],
	["Orientēšanās",		19],
	["Ziemas sports",		20],
	["Pokers",				21],
	["Peldēšana",			22],
	["Regbijs",				23],
	["Bokss",				24],
	["Telpu futbols",		25],
	["Golfs",				26],
	["Cīņas sports",		27],
	["Spēka sports",		28],
	["Ekstrēmais sports",	29] ]
	belongs_to :sport
	validates  :url, :sport_id, presence: true
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
    @sportss = Sport.joins(:feeds)
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:url, :sport_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.url_field :url, size: 65 %><br>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br>
    <%= f.select :sport_id, Feed::SPORTS,
                  prompt: '' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing Feeds</h1>
<table>
  <% @feeds.each do |feed| %>
    <% @sportss.where(id: feed.sport_id).find_each do |sport| %>
    <tr>
    <td><%= sport.sports %></td>
        <td><%= feed.url %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    <% end %>
  </table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @feed.sport_id %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>