config/routes.rb
Projekts::Application.routes.draw do
  get 'admin' => 'admin#index'

   controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :feeds

  resources :user_sports

  get 'admin/index' 

  get 'sessions/new', as: 'sign_up'

  post 'user_sports' => 'user_sports#create'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :news

  resources :my_profiles

  resources :sports

  get "users/index"

  resources :users

  root 'news#index', via: :all
  

end

app/models/sport.rb
class Sport < ActiveRecord::Base
	validates :sports, presence: true, uniqueness: true
	has_many :users, through: :user_sports
	has_many :feed_entries
	has_many :user_sports
	has_many :feeds
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index

    @sports = Sport.all
   # @izv_sport = Sport.joins(user_sports: :user)
    @izv_sport = Sport.joins(user_sports: :user).where(users: {:id => (session[:user_id])})
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
     @sports = Sport.find(params[:id])
    @izv_sport = Sport.joins(user_sports: :user)
  end

  # GET /sports/new
  def new
    @sports = Sport.new
    @izv_sport = Sport.joins(user_sports: :user)
  end

  # GET /sports/1/edit
  def edit
    @sports = Sport.find(params[:id])
    @izv_sport = Sport.joins(user_sports: :user)
  end

  # POST /sports
  # POST /sports.json
  def create
    @sports = Sport.new(sport_params)

    respond_to do |format|
      if @sports.save
        format.html { redirect_to sports_url, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    @sports = Sport.find(params[:id])
    respond_to do |format|
      if @sports.update(sport_params)
        format.html { redirect_to sports_url, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:sports, :image)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sports) do |f| %>
  <% if @sports.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sports.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sports %><br>
    <%= f.text_field :sports %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/_sport.html.erb
	<tr>
       <td> <%= sport.sports -%></td>
       <td><%= button_to 'pievienot', user_sports_path(sport_id: sport) %></td>
   </tr>

app/views/sports/_sport1.html.erb
<% @izv_sport.each do |sport1| %>
<tr>
       <td> <%= sport1.sports -%></td>
       <td><%= button_to 'Noņemt', {:controller => "user_sports", :action => 'destroy', :id => sport1.id}, method: :delete %>
   </tr>
   <% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing Sports</h1>
<table>
  <thead>
    <tr>
      <th>Sports</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= image_tag(sport.image, class: 'list_image') %></td>
        <td><%= sport.sports %></td>
        <td><%= sport.id %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>