config/routes.rb
Projekts::Application.routes.draw do
  get 'admin' => 'admin#index'

   controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :feeds

  resources :user_sports

  get 'admin/index' 

  get 'sessions/new', as: 'sign_up'

  post 'user_sports' => 'user_sports#create'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :news

  resources :my_profiles

  resources :sports

  get "users/index"

  resources :users

  root 'news#index', via: :all
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projekts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
		
	<div id="par">	
		<ul>
			<li><%= link_to 'Ziņas', news_index_path %></li>
			<%if session[:user_id]==nil%>
			<li><%= link_to 'Login', login_path %></li>
			<li><%= link_to 'Piereģistrēties', new_user_path %></li>
			<%end%>	
			<%if session[:user_id]%>
				<li><%= link_to 'Profils', edit_my_profile_path(id: User.find(session[:user_id])) %></li>
			<%end%>
				<%if session[:user_id]==1 %>
					<li><%= link_to 'Feeds', feeds_path %></li>
					<li><%= link_to 'Sports', sports_path %></li>
					<li><%= link_to 'Users', users_path %></li>
					<li><%= link_to 'User_sports', user_sports_path %></li>
				<% end %>
		</ul>
	</div>	
	<div id="banner1">
		<%= image_tag "sports1.jpg" %>
	</div>
	<div id="columns">
		<div id="side">
				<p id="notice"><%= notice %></p>  
			<%if session[:user_id] %>
				<div><strong>Jūs esiet ierakstījies kā: </strong>
					<%= session[:username] %>
				</div>

				<div id="logout">
					<%= button_to 'Logout', logout_path, method: :delete %>
				</div>
				<h4>Tavi porta veidi:</h4>
				<div id="sporta_veidi_izveleti">
					<table>
						<%= render "sports/sport1" %>
					</table>					
				</div>

				<h4>Sporta veidi:</h4>
				<div id="sporta_veidi">
					<table>
						<%= render @sports %>
					</table>
				</div>
			<% end %>
		</div>
	</div>
	<div id="main">
		<%= yield %>
	</div>
			
	<div id="banner2">
		<%= image_tag "sports2.jpg" %>
	</div>

</body>
</html>